# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateField(auto_now=True),
        ),
    ]
